AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Grabs services description
Parameters:
  Environment:
    Type: String
    Default: development
Resources:
  awsBidsAlexaSkill:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: alexa/
      Timeout: 300
      Policies:
      - AmazonSESFullAccess
      - AmazonSNSFullAccess
      - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          SNS_EMAIL_TOPIC: !Ref awsBidsAlexaSns
          SNS_COMPLIANCE_TOPIC: !Ref awsBidsComplianceSns
          SNS_TAX_TOPIC: !Ref awsBidsTaxSns
          SNS_DIRECTORS_TOPIC: !Ref awsBidsDirectorsSns
          DYNAMODB_TABLE: !Ref bidsLoginTable
          DYNAMODB_NOTES_TABLE: !Ref bidsNotesTable

  awsBidsEmailerSkill:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: emailer/
      Timeout: 300
      Policies:
      - AmazonSESFullAccess
      Events:
        SNS:
          Type: SNS
          Properties:
            Topic: !Ref awsBidsAlexaSns

  awsBidsServicesSkill:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: services/
      Timeout: 300
      Policies:
      - AmazonSESFullAccess
      Events:
        SNS:
          Type: SNS
          Properties:
            Topic: !Ref awsBidsServicesSns
      Environment:
        Variables:
          SNS_EMAIL_TOPIC: !Ref awsBidsAlexaSns

  awsBidsComplianceSkill:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: compliance/
      Timeout: 300
      Policies:
      - AmazonS3FullAccess
      - AmazonSESFullAccess
      Events:
        SNS:
          Type: SNS
          Properties:
            Topic: !Ref awsBidsComplianceSns
      Environment:
        Variables:
          COMPLIANCE_BUCKETNAME: !Ref ComplianceS3Bucket
          SNS_EMAIL_TOPIC: !Ref awsBidsAlexaSns

  ComplianceS3Bucket:
    Type: AWS::S3::Bucket

  awsBidsComplianceSns:
    Type: "AWS::SNS::Topic"
    Properties: 
      DisplayName: AWS Bids Compliance Topic
      TopicName: !Join ["-", [ awsBidsComplianceSns, Environment ]]

  awsBidsTaxSkill:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: tax/
      Timeout: 300
      Policies:
      - AmazonSESFullAccess
      Events:
        SNS:
          Type: SNS
          Properties:
            Topic: !Ref awsBidsTaxSns
      Environment:
        Variables:
          SNS_EMAIL_TOPIC: !Ref awsBidsAlexaSns

  awsBidsDirectorsSkill:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: directors/
      Timeout: 300
      Policies:
      - AmazonSESFullAccess
      Events:
        SNS:
          Type: SNS
          Properties:
            Topic: !Ref awsBidsDirectorsSns
      Environment:
        Variables:
          SNS_EMAIL_TOPIC: !Ref awsBidsAlexaSns

  awsBidsTaxSns:
    Type: "AWS::SNS::Topic"
    Properties: 
      DisplayName: AWS Bids Tax Topic
      TopicName: !Join ["-", [ awsBidsTaxSns, Environment ]]

  awsBidsDirectorsSns:
    Type: "AWS::SNS::Topic"
    Properties: 
      DisplayName: AWS Bids Tax Topic
      TopicName: !Join ["-", [ awsBidsDirectorsSns, Environment ]]

  awsBidsAlexaSns:
    Type: "AWS::SNS::Topic"
    Properties: 
      DisplayName: AWS Bids Alexa Topic
      TopicName: !Join ["-", [ awsBidsAlexaSns, Environment ]]

  awsBidsServicesSns:
    Type: "AWS::SNS::Topic"
    Properties: 
      DisplayName: AWS Bids Services Topic
      TopicName: !Join ["-", [ awsBidsServicesSns, Environment ]]

  bidsServicesTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        -
          AttributeName: 'ServiceName'
          AttributeType: 'S'
      KeySchema:
        -
          AttributeName: "ServiceName"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: !Join ["-", ["bidsServicesTable", Environment ]]

  bidsLoginTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "Organisation"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "Organisation"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: !Join ["-", ["bidsLoginTable", Environment ]]

  bidsNotesTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "UserEmail"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "UserEmail"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: "bidsNotesTable"
